In [1]:
!pip install tensorflow
import tensorflow as tf


Defaulting to user installation because normal site-packages is not writeable


2023-07-16 13:32:46.756853: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-16 13:32:46.787691: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-16 13:32:46.909909: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-16 13:32:46.911019: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-16 13:32:48.210879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [2]:
# scalar examples

# Create scalar tensors
scalar1 = tf.constant(5)  # Scalar with value 5
scalar2 = tf.constant(3)  # Scalar with value 3

# Perform scalar operations
addition = tf.add(scalar1, scalar2)  # Addition
subtraction = tf.subtract(scalar1, scalar2)  # Subtraction
multiplication = tf.multiply(scalar1, scalar2)  # Multiplication
division = tf.divide(scalar1, scalar2)  # Division


# Print the results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: tf.Tensor(8, shape=(), dtype=int32)
Subtraction: tf.Tensor(2, shape=(), dtype=int32)
Multiplication: tf.Tensor(15, shape=(), dtype=int32)
Division: tf.Tensor(1.6666666666666667, shape=(), dtype=float64)


In [3]:
 #vector examples
vector1 = tf.constant([1, 2, 3])  # Vector [1, 2, 3]
vector2 = tf.constant([4, 5, 6])  # Vector [4, 5, 6]

# Perform vector operations
elementwise_sum = tf.add(vector1, vector2)  # Elementwise sum

# [1 + 4, 2 + 5, 6 + 3] = [5, 7, 9]

elementwise_product = tf.multiply(vector1, vector2)  # Elementwise product

#[1 * 4, 2 * 5, 6 * 3] = [4, 10, 18]
dot_product = tf.tensordot(vector1, vector2, axes=1)  # Dot product

# sum of our elementwise product


print(elementwise_sum)
print(elementwise_product)
print(dot_product)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)


In [5]:
#  matrix tensors
matrix1 = tf.constant([[1, 2], [3, 4]])  # 2x2 matrix [[1, 2], [3, 4]]
matrix2 = tf.constant([[5, 6], [7, 8]])  # 2x2 matrix [[5, 6], [7, 8]]
matrix3 = tf.constant([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix

# Perform matrix operations
matrix_sum = tf.add(matrix1, matrix2)  # Matrix addition
# [1 + 5, 2+ 6]    [6, 8]
#[3 + 7, 4 + 8] =  [10, 12]

matrix_product = tf.matmul(matrix1, matrix2)  # Matrix multiplication
# [1 * 5 + 2 * 7. 1 * 6 + 2 * 8]  [19, 22]
#[3 * 5 + 4 * 7, 3 * 6 + 4 * 8] = [43,50]

transposed_matrix = tf.transpose(matrix3)
# [1, 4]
# [2, 5]
# [3, 6]
# Print the results
print("Matrix Sum:")
print(matrix_sum)
print("Matrix Product:")
print(matrix_product)

print("Original Matrix:")
print(matrix3)
print("Transposed Matrix:")
print(transposed_matrix)


Matrix Sum:
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Matrix Product:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Original Matrix:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Transposed Matrix:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [6]:
# Hadamard Product
# Create tensor 1
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]])  # 2x3 tensor

# Create tensor 2
tensor2 = tf.constant([[2, 4, 6], [8, 10, 12]])  # 2x3 tensor

#[1 * 2, 2 * 4, 3 * 6]
#[4 * 8, 5 * 10, 6 * 12]

# Perform Hadamard product
hadamard_product = tf.multiply(tensor1, tensor2)

# Print the result
print("Tensor 1:")
print(tensor1)
print("Tensor 2:")
print(tensor2)
print("Hadamard Product:")
print(hadamard_product)



Tensor 1:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor 2:
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
Hadamard Product:
tf.Tensor(
[[ 2  8 18]
 [32 50 72]], shape=(2, 3), dtype=int32)


In [ ]:
## matrix multiplication example
# Create matrix tensors
matrix1 = tf.constant([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
matrix2 = tf.constant([[7, 8], [9, 10], [11, 12]])  # 3x2 matrix

# Perform matrix multiplication
matrix_product = tf.matmul(matrix1, matrix2)


# Print the result
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Matrix Product:")
print(matrix_product)

In [7]:
# reduced mean
# Create a tensor
tensor = tf.constant([1, 2, 3, 4, 5])

# Reduce the tensor using mean
reduced_mean = tf.reduce_mean(tensor)

#[1 + 2 + 3 +4 + 5]
#/ 5

# Print the result
print("Tensor:")
print(tensor)
print("Reduced Mean:")
print(reduced_mean)

Tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Reduced Mean:
tf.Tensor(3, shape=(), dtype=int32)


In [8]:
#Norm example
# Create a tensor
tensor = tf.constant([1, 2, 3, 4], dtype=tf.float32)

# Calculate the L2 norm of the tensor
l2_norm = tf.norm(tensor, ord=2)

#sqrt[1^2 + 2^2 + 3^2 + 4^2]

# Calculate the L1 norm of the tensor
l1_norm = tf.norm(tensor, ord=1)

#1 + 2 + 3 + 4


# Print the results
print("Tensor:")
print(tensor)
print("L2 Norm:")
print(l2_norm)
print("L1 Norm:")
print(l1_norm)

Tensor:
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
L2 Norm:
tf.Tensor(5.477226, shape=(), dtype=float32)
L1 Norm:
tf.Tensor(10.0, shape=(), dtype=float32)
